/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CobrancasRouteImport } from './routes/cobrancas'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PagarTokenRouteImport } from './routes/pagar.$token'
import { Route as ClientesImportarRouteImport } from './routes/clientes.importar'
import { Route as ClientesCompletarRouteImport } from './routes/clientes.completar'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as ApiAsaasWebhookRouteImport } from './routes/api.asaas-webhook'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ApiPublicPlanWebhookRouteImport } from './routes/api.public.plan-webhook'
import { Route as ApiPublicHooksNotifyExpiringRouteImport } from './routes/api.public.hooks.notify-expiring'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancasRoute = CobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PagarTokenRoute = PagarTokenRouteImport.update({
  id: '/pagar/$token',
  path: '/pagar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesImportarRoute = ClientesImportarRouteImport.update({
  id: '/clientes/importar',
  path: '/clientes/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesCompletarRoute = ClientesCompletarRouteImport.update({
  id: '/clientes/completar',
  path: '/clientes/completar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAsaasWebhookRoute = ApiAsaasWebhookRouteImport.update({
  id: '/api/asaas-webhook',
  path: '/api/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPlanWebhookRoute = ApiPublicPlanWebhookRouteImport.update({
  id: '/api/public/plan-webhook',
  path: '/api/public/plan-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotifyExpiringRoute =
  ApiPublicHooksNotifyExpiringRouteImport.update({
    id: '/api/public/hooks/notify-expiring',
    path: '/api/public/hooks/notify-expiring',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/asaas-webhook': typeof ApiAsaasWebhookRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/completar': typeof ClientesCompletarRoute
  '/clientes/importar': typeof ClientesImportarRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/api/public/plan-webhook': typeof ApiPublicPlanWebhookRoute
  '/api/public/hooks/notify-expiring': typeof ApiPublicHooksNotifyExpiringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/asaas-webhook': typeof ApiAsaasWebhookRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/completar': typeof ClientesCompletarRoute
  '/clientes/importar': typeof ClientesImportarRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/admin': typeof AdminIndexRoute
  '/clientes': typeof ClientesIndexRoute
  '/api/public/plan-webhook': typeof ApiPublicPlanWebhookRoute
  '/api/public/hooks/notify-expiring': typeof ApiPublicHooksNotifyExpiringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/asaas-webhook': typeof ApiAsaasWebhookRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/completar': typeof ClientesCompletarRoute
  '/clientes/importar': typeof ClientesImportarRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/clientes/': typeof ClientesIndexRoute
  '/api/public/plan-webhook': typeof ApiPublicPlanWebhookRoute
  '/api/public/hooks/notify-expiring': typeof ApiPublicHooksNotifyExpiringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/planos'
    | '/whatsapp'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/asaas-webhook'
    | '/clientes/$id'
    | '/clientes/completar'
    | '/clientes/importar'
    | '/pagar/$token'
    | '/admin/'
    | '/clientes/'
    | '/api/public/plan-webhook'
    | '/api/public/hooks/notify-expiring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/planos'
    | '/whatsapp'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/asaas-webhook'
    | '/clientes/$id'
    | '/clientes/completar'
    | '/clientes/importar'
    | '/pagar/$token'
    | '/admin'
    | '/clientes'
    | '/api/public/plan-webhook'
    | '/api/public/hooks/notify-expiring'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/planos'
    | '/whatsapp'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/asaas-webhook'
    | '/clientes/$id'
    | '/clientes/completar'
    | '/clientes/importar'
    | '/pagar/$token'
    | '/admin/'
    | '/clientes/'
    | '/api/public/plan-webhook'
    | '/api/public/hooks/notify-expiring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CobrancasRoute: typeof CobrancasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiAsaasWebhookRoute: typeof ApiAsaasWebhookRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesCompletarRoute: typeof ClientesCompletarRoute
  ClientesImportarRoute: typeof ClientesImportarRoute
  PagarTokenRoute: typeof PagarTokenRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ApiPublicPlanWebhookRoute: typeof ApiPublicPlanWebhookRoute
  ApiPublicHooksNotifyExpiringRoute: typeof ApiPublicHooksNotifyExpiringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobrancas': {
      id: '/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof CobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pagar/$token': {
      id: '/pagar/$token'
      path: '/pagar/$token'
      fullPath: '/pagar/$token'
      preLoaderRoute: typeof PagarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/importar': {
      id: '/clientes/importar'
      path: '/clientes/importar'
      fullPath: '/clientes/importar'
      preLoaderRoute: typeof ClientesImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/completar': {
      id: '/clientes/completar'
      path: '/clientes/completar'
      fullPath: '/clientes/completar'
      preLoaderRoute: typeof ClientesCompletarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asaas-webhook': {
      id: '/api/asaas-webhook'
      path: '/api/asaas-webhook'
      fullPath: '/api/asaas-webhook'
      preLoaderRoute: typeof ApiAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/plan-webhook': {
      id: '/api/public/plan-webhook'
      path: '/api/public/plan-webhook'
      fullPath: '/api/public/plan-webhook'
      preLoaderRoute: typeof ApiPublicPlanWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-expiring': {
      id: '/api/public/hooks/notify-expiring'
      path: '/api/public/hooks/notify-expiring'
      fullPath: '/api/public/hooks/notify-expiring'
      preLoaderRoute: typeof ApiPublicHooksNotifyExpiringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CobrancasRoute: CobrancasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  WhatsappRoute: WhatsappRoute,
  ApiAsaasWebhookRoute: ApiAsaasWebhookRoute,
  ClientesIdRoute: ClientesIdRoute,
  ClientesCompletarRoute: ClientesCompletarRoute,
  ClientesImportarRoute: ClientesImportarRoute,
  PagarTokenRoute: PagarTokenRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ApiPublicPlanWebhookRoute: ApiPublicPlanWebhookRoute,
  ApiPublicHooksNotifyExpiringRoute: ApiPublicHooksNotifyExpiringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
