/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CobrancasRouteImport } from './routes/cobrancas'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as PagarTokenRouteImport } from './routes/pagar.$token'
import { Route as ClientesImportarRouteImport } from './routes/clientes.importar'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancasRoute = CobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarTokenRoute = PagarTokenRouteImport.update({
  id: '/pagar/$token',
  path: '/pagar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesImportarRoute = ClientesImportarRouteImport.update({
  id: '/clientes/importar',
  path: '/clientes/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/whatsapp': typeof WhatsappRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/importar': typeof ClientesImportarRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/whatsapp': typeof WhatsappRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/importar': typeof ClientesImportarRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/cobrancas': typeof CobrancasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/whatsapp': typeof WhatsappRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/importar': typeof ClientesImportarRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/whatsapp'
    | '/clientes/$id'
    | '/clientes/importar'
    | '/pagar/$token'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/whatsapp'
    | '/clientes/$id'
    | '/clientes/importar'
    | '/pagar/$token'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/whatsapp'
    | '/clientes/$id'
    | '/clientes/importar'
    | '/pagar/$token'
    | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CobrancasRoute: typeof CobrancasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  WhatsappRoute: typeof WhatsappRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesImportarRoute: typeof ClientesImportarRoute
  PagarTokenRoute: typeof PagarTokenRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobrancas': {
      id: '/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof CobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar/$token': {
      id: '/pagar/$token'
      path: '/pagar/$token'
      fullPath: '/pagar/$token'
      preLoaderRoute: typeof PagarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/importar': {
      id: '/clientes/importar'
      path: '/clientes/importar'
      fullPath: '/clientes/importar'
      preLoaderRoute: typeof ClientesImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CobrancasRoute: CobrancasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  WhatsappRoute: WhatsappRoute,
  ClientesIdRoute: ClientesIdRoute,
  ClientesImportarRoute: ClientesImportarRoute,
  PagarTokenRoute: PagarTokenRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
