// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Response(
        'Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are set.',
        { status: 500 }
      );
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    // 1. Authorization header
    let authHeader = request.headers.get('authorization');

    // 2. Cookie fallback (useful for SSR/Refresh)
    if (!authHeader) {
      const cookieHeader = request.headers.get('cookie');
      if (cookieHeader) {
        // Look for any Supabase auth token in cookies
        const tokenMatch = cookieHeader.match(/sb-[a-zA-Z0-9]+-auth-token=([^;]+)/);
        if (tokenMatch?.[1]) {
          try {
            const authData = JSON.parse(decodeURIComponent(tokenMatch[1]));
            const access_token = Array.isArray(authData) ? authData[0] : authData?.access_token;
            if (access_token) {
              authHeader = `Bearer ${access_token}`;
            }
          } catch (e) {
            // Failed to parse cookie
          }
        }
      }
    }

    // 3. Last resort: URL parameter fallback (useful for testing or specific client environments)
    if (!authHeader) {
      const url = new URL(request.url);
      const access_token = url.searchParams.get('access_token');
      if (access_token) {
        authHeader = `Bearer ${access_token}`;
      }
    }

    if (!authHeader) {
      // For debugging in preview, let's see what headers we DO have
      const headerKeys = Array.from(request.headers.keys()).join(', ');
      throw new Response(`Unauthorized: No authorization header provided. Available: ${headerKeys}`, { status: 401 });
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response('Unauthorized: Invalid token', { status: 401 });
    }

    if (!data.claims.sub) {
      throw new Response('Unauthorized: No user ID found in token', { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    })
  }
)
